/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : string,
  'date' : string,
  'name' : string,
  'time' : string,
  'treatment' : string,
  'email' : string,
  'notes' : string,
  'timestamp' : bigint,
  'phone' : string,
  'treatmentDone' : [] | [boolean],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ShoppingItem {
  'currency' : string,
  'productName' : string,
  'productDescription' : string,
  'priceInCents' : bigint,
  'quantity' : bigint,
}
export interface StripeConfiguration {
  'secretKey' : string,
  'allowedCountries' : Array<string>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<[Array<ShoppingItem>, string, string], string>,
  'deleteAppointment' : ActorMethod<[bigint], undefined>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markTreatmentDone' : ActorMethod<[bigint, boolean], undefined>,
  'rescheduleAppointment' : ActorMethod<[bigint, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitAppointment' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'updateAppointmentStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];