/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'treatment' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'treatmentDone' : IDL.Opt(IDL.Bool),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ShoppingItem = IDL.Record({
  'currency' : IDL.Text,
  'productName' : IDL.Text,
  'productDescription' : IDL.Text,
  'priceInCents' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'secretKey' : IDL.Text,
  'allowedCountries' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func([IDL.Vec(ShoppingItem), IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteAppointment' : IDL.Func([IDL.Nat], [], []),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markTreatmentDone' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'rescheduleAppointment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'treatment' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'treatmentDone' : IDL.Opt(IDL.Bool),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ShoppingItem = IDL.Record({
    'currency' : IDL.Text,
    'productName' : IDL.Text,
    'productDescription' : IDL.Text,
    'priceInCents' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'secretKey' : IDL.Text,
    'allowedCountries' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func([IDL.Vec(ShoppingItem), IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteAppointment' : IDL.Func([IDL.Nat], [], []),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markTreatmentDone' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'rescheduleAppointment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };